#
/vis/scene/create
/vis/open OGL 600x600-0+0
#
/vis/viewer/set/autoRefresh true
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume

# Draw coordinate axes:
/vis/scene/add/axes 0 0 0 20 cm

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

# Draw hits at end of event:
/vis/scene/add/hits

/vis/scene/endOfEventAction accumulate

# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true

/run/verbose 2
/process/verbose 2
/cuts/verbose 2
/event/verbose 2
/tracking/verbose 2
/control/verbose 2
/gps/verbose 0

/gps/particle gamma

/gps/number 1
/gps/pos/type Point
# /gps/pos/shape Circle
# /gps/pos/radius 0.5 mm
/gps/pos/centre  0 0 0  mm
/gps/energy 200 GeV
/gps/ang/type iso
/gps/ang/mintheta 90 deg
/gps/ang/maxtheta 90 deg

#/run/setCut 10 mm

#/random/setSavingFlag 1
/random/resetEngineFrom
/geometry/navigator/check_mode true
/run/beamOn 1

